package com.sati.model;
// Generated 22 janv. 2023 � 03:52:28 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Participer generated by hbm2java
 */
@Entity
@Table(name = "participer", catalog = "emargementsimplon_bd")
public class Participer implements java.io.Serializable {

	private Integer idParticipant;
	private String nomParticipant;
	private String prenomParticipant;
	private int numeroParticipant;
	private String adresseParticipant;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Participer() {
	}

	public Participer(String nomParticipant, String prenomParticipant, int numeroParticipant,
			String adresseParticipant) {
		this.nomParticipant = nomParticipant;
		this.prenomParticipant = prenomParticipant;
		this.numeroParticipant = numeroParticipant;
		this.adresseParticipant = adresseParticipant;
	}

	public Participer(String nomParticipant, String prenomParticipant, int numeroParticipant, String adresseParticipant,
			Set<Utilisateur> utilisateurs) {
		this.nomParticipant = nomParticipant;
		this.prenomParticipant = prenomParticipant;
		this.numeroParticipant = numeroParticipant;
		this.adresseParticipant = adresseParticipant;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PARTICIPANT", unique = true, nullable = false)
	public Integer getIdParticipant() {
		return this.idParticipant;
	}

	public void setIdParticipant(Integer idParticipant) {
		this.idParticipant = idParticipant;
	}

	@Column(name = "NOM_PARTICIPANT", nullable = false, length = 65535)
	public String getNomParticipant() {
		return this.nomParticipant;
	}

	public void setNomParticipant(String nomParticipant) {
		this.nomParticipant = nomParticipant;
	}

	@Column(name = "PRENOM_PARTICIPANT", nullable = false, length = 65535)
	public String getPrenomParticipant() {
		return this.prenomParticipant;
	}

	public void setPrenomParticipant(String prenomParticipant) {
		this.prenomParticipant = prenomParticipant;
	}

	@Column(name = "NUMERO_PARTICIPANT", nullable = false)
	public int getNumeroParticipant() {
		return this.numeroParticipant;
	}

	public void setNumeroParticipant(int numeroParticipant) {
		this.numeroParticipant = numeroParticipant;
	}

	@Column(name = "ADRESSE_PARTICIPANT", nullable = false, length = 65535)
	public String getAdresseParticipant() {
		return this.adresseParticipant;
	}

	public void setAdresseParticipant(String adresseParticipant) {
		this.adresseParticipant = adresseParticipant;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "participers")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
